spring:
  datasource:
    url: jdbc:postgresql://${connection:localhost}:5432/authentication-dev
    username: dbuser
    password: 12345
  jpa:
    show-sql: true

logging:
  file: logs/login/app.log
  level:
    root: INFO