spring:
  datasource:
    url: jdbc:postgresql://${connection:localhost}:5432/authentication-qa
    username: dbuser
    password: 12345

logging:
  file: logs/login/app.log
  level:
    root: ERROR
  pattern:
    console: